name: Rootless-Store Debuggable-App CD

on:
  push:
    # tag 触发发布
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    environment: release

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Grant gradlew permission
        run: chmod +x ./gradlew

      # 构建 debug APK
      - name: Build debug APK
        run: ./gradlew assembleGithub
        env:
          DEBUG_STORE_PASSWORD: ${{ secrets.DEBUG_STORE_PASSWORD }}
          DEBUG_KEY_ALIAS: ${{ secrets.DEBUG_KEY_ALIAS }}
          DEBUG_KEY_PASSWORD: ${{ secrets.DEBUG_KEY_PASSWORD }}

      # 读取 asset/markdown/release/<tag>.md 作为发布说明
      - name: Upload Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: app/build/outputs/apk/**/*.apk
          body_path: asset/markdown/release/${{ github.ref_name }}.md
